// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNNSaXARj84oMP2Eom-_mKhXblLcNkQY',
    appId: '1:695344756481:web:b09759e938e330509d0d00',
    messagingSenderId: '695344756481',
    projectId: 'dirayapp-93e86',
    authDomain: 'dirayapp-93e86.firebaseapp.com',
    storageBucket: 'dirayapp-93e86.appspot.com',
    measurementId: 'G-YJDNZWMTXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzUSZr2Xghs3iHvGr2NWO4Og-gIlxuDE',
    appId: '1:695344756481:android:0a01586080c1daa09d0d00',
    messagingSenderId: '695344756481',
    projectId: 'dirayapp-93e86',
    storageBucket: 'dirayapp-93e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVsjPaAMQf29DMyxHibat6RWgnf3ZDLiI',
    appId: '1:695344756481:ios:dbbdd9a4076334fe9d0d00',
    messagingSenderId: '695344756481',
    projectId: 'dirayapp-93e86',
    storageBucket: 'dirayapp-93e86.appspot.com',
    iosClientId: '695344756481-79qo6bva6nil68h3o0p4h4l04avv1q4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVsjPaAMQf29DMyxHibat6RWgnf3ZDLiI',
    appId: '1:695344756481:ios:95c2a2fbcfa5f6d39d0d00',
    messagingSenderId: '695344756481',
    projectId: 'dirayapp-93e86',
    storageBucket: 'dirayapp-93e86.appspot.com',
    iosClientId: '695344756481-bu2paapba2l6m9cvmpt0bvrtldgg3pid.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp.RunnerTests',
  );
}
